# скрипт для docker-compose

services:
  web:
    # Берем Dockerfile из каталога orders
    build:
      context: ./orders
      dockerfile: Dockerfile
#    build: ./orders
    # Запускаем сервер gunicorn
    command: gunicorn orders.wsgi:application --bind 0.0.0.0:8000
#    volumes:
#      - ./orders/:/usr/src/app/
    # Открываем порт 8000 наружу
    expose:
      - 8000
    # Открываем порт 8000 внутри и снаружи
#    ports:
#      - 8000:8000
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env
    # Дожидаемся запуска контейнера db
    depends_on:
      - db

  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./nginx
    # Подключаем статические и медиа файлы
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
